### ISSUE TITLE
4-shank probe track  

### ISSUE THREAD

**Issue by xcccc402** [petersaj/AP_histology#10]
Hi. I am wondering what would would you sugges when drawing where probe is. Should I draw a line in the middle of dii track? Also, is there any update for 4-shank probe track that I might miss.

**Comment by petersaj** [comment]
I usually draw the line whenever I see any (strong) DiI on a slice, and at the end it estimates the probe trajectory as the line of best fit through all the points you drew.

I haven't added anything special for 4-shanks - is there some feature that would make it easier? I might think treating them as 4 separate trajectories would be the most straightforward
