### ISSUE TITLE
Slices thickness

### ISSUE THREAD

**Issue by elladulko** [petersaj/AP_histology#11]
Hi Peter! Thanks for sharing your code. I will try to run it for my samples. I am wondering how thick you cut your slices? I'm guessing the thinner you slice, the more slices with DiI stain you get, and maybe it's easier to assess the probe trajectory? Let me know. 

Ela

**Comment by petersaj** [comment]
Hi Ela - we do 100um slices, it's as thick as we can go and the localization of the probe is still great, so no benefit for us in going thinner.

**Comment by elladulko** [comment]
Ok. Awesome. Thanks!
