### ISSUE TITLE
integrate deepslice

### ISSUE THREAD

**Issue by chongtianyifa** [petersaj/AP_histology#14]
Hi Andrew,

Sorry to bother you again. I am curious about whether it is possible to integrate the output of deepslice to initiate the atlas plane for the corresponding histology images in AP_grab_histology_ccf? I attached an example output from deepslice (https://www.deepslice.com.au/).
[results (1).zip](https://github.com/petersaj/AP_histology/files/9074423/results.1.zip)

It saves the four edge points of each template slice in RAS coordinate system. I think I can convert them into Allen coordinates (a file with an example plane was attached, each column is the coordinate of an edge point in the standard Allen space). How can I use them to initialize the altas plane for corresponding histology images in the AP_grab_histology_ccf?
[points of edge in allen space.csv](https://github.com/petersaj/AP_histology/files/9075560/points.of.edge.in.allen.space.csv)

Thanks advance for the help.

**Comment by chongtianyifa** [comment]
Hi Andrew,

Thanks for the help. I think I successfully loaded the output of deepslice by transforming their four coordinates into CCF coordinates. Using these four coordinates, which determine the atlas slice plane, I got the norm and center of the plane for corresponding histology slice. Then I added these norms to gui_data (gui_data.Cam_Vector) as the camera view angle and center points to gui_data (gui_data.Cam_Target) as the camera target. In the 'update_histology_slice' function, two lines were added if no saved atlas position:
        view(gui_data.Cam_Vector(gui_data.curr_histology_slice,:)) % If there's no saved atlas position, loading atlas to plane found by deepslice
        gui_data.atlas_slice_point = gui_data.Cam_Target(gui_data.curr_histology_slice,:);
Now the slice plane will switch to the plane found by deepslice.

**Comment by petersaj** [comment]
Great, sounds like it's working then? Does the deepslice alignment work well enough for you that you can essentially skip the step of manually finding the CCF slices?

If so, could you share the code you wrote to use it? Sounds like this is a modified version of `AP_grab_histology_ccf`, which loads/converts the deepslice output and initializes the CCF alignments for each slice?

**Comment by chongtianyifa** [comment]
It works for me now. I use the deepslice output to expedite the alignment, especially when individual slices were not continuously sectioned/imaged. For most cases, I still need to modify the angle and position a little.

Sure. I attached the modifed demo_histology_pipeline.m and AP_grab_histology_ccf.m
Here is the modification:
!!important: the order of images should be kept the same between deepslice output (a row for each image) and the .tiff images!!
1) set directory to use deepslice output (line 42-43 in demo_histology_pipeline)
2) initiate plane determined by deepslice (line 73-83 in AP_grab_histology_ccf)
3) update update_histology_slice function in AP_grab_histology_ccf
[AP_grab_histology_ccf.zip](https://github.com/petersaj/AP_histology/files/9163687/AP_grab_histology_ccf.zip)

**Comment by petersaj** [comment]
Thanks! The DeepSlice page is throwing errors for me (gave me one output on a test, but then started giving URL errors when I try to download subsequent alignments), I'll try it again another time

**Comment by petersaj** [comment]
This is old, closing this. 

I did recently try looking at this again: the DeepSlice is often broken for me and doesn't actually provide alignments. When it does, they're not as good as manual alignments, so it doesn't look accurate enough to actually help at the moment.
