### ISSUE TITLE
Export aligned CCF as vector graphics file

### ISSUE THREAD

**Issue by ckfaber** [petersaj/AP_histology#19]
Hello! 

First off, this is amazing work, thank you for sharing it! I'm just getting started with using AP_histology to register coronal slices containing NeuroNexus implant tracts, but I'm wondering: 

Is there a way to export the slice with aligned CCF as a vector graphic file, for working in Illustrator or Photoshop to generate publication figures? 

I'm also hoping to adapt this pipeline to improve automated ROI annotation for quantification of labeled cells in tracing experiments. Very new to working with images, so any suggestions are very welcome. Thanks so much!! 

Best,
Chelsea

**Comment by petersaj** [comment]
Hi Chelsea - probably the easiest way is save the matlab figure you want to export as an EPS (file > save as > .eps), then you should be able to work with it in Illustrator. 

Matlab's got some funny things about exporting images to EPS, but they've improved with time so it'll be best with the latest version. One classic thing is that it sometimes splits the image into 2 diagonally, but I think that's been fixed. Running this command to change the figure renderer also sometimes helps fix bugs: `set(gcf,'Renderer','painters');`

Let me know if there are any issues with that, hope your adaptation for labelled cells works well, feel free to let me know if any specific questions come up.
