### ISSUE TITLE
smooth function not found

### ISSUE THREAD

**Issue by HernandoMV** [petersaj/AP_histology#2]
Hi, where is the 'smooth' function from? 
See error:
Error in demo_histology_pipeline (line 32)
AP_process_histology(im_path,resize_factor,slice_images);

Undefined function 'smooth' for input arguments of type 'double'.

**Comment by petersaj** [comment]
That's in the curve fitting toolbox (https://uk.mathworks.com/help/curvefit/smooth.html), are you not able to download it?

**Comment by HernandoMV** [comment]
Thanks, didn't know this was a requirement. I might have missed it 👍
