### ISSUE TITLE
Is there a way to verify the cluster's anatomical location? 

### ISSUE THREAD

**Issue by elladulko** [petersaj/AP_histology#20]
Hey! Our lab is using your code to register clusters after phy curation to the anatomical location. I am wondering if there is a way to double check if the predicted location is correct. For example I can imagine that we could see if the firing frequency/amplitude of one cluster assigned to CA1 is a typical frequency described for CA1. 
But I don't know if there is any datasets available for electrophysiological properties of the cell to run this kind of analysis. Maybe you have some insight about it? 
Do you verify the histology output in any other way? 
I appreciate your advice.
Ela

**Comment by petersaj** [comment]
Hi Ela - I think making something like an "electrophysiological atlas" to characterize cells by location is one of the long-term goals of the International Brain Lab, they are collecting a massive dataset at the moment but I wouldn't expect something like that for a while still.

Barring that, the only sanity checks I know of are things like known LFP oscillations, clusters of firing properties, expected responses, spatial gaps between units, etc. So if you're recording around CA1 for example, hopefully you'll see a characteristic lack of spikes in the white matter above and below.

Would that kind of thing be good enough for your purposes, or have you had particular trouble identifying the location?

**Comment by AthiemoneZero** [comment]
> Hi Ela - I think making something like an "electrophysiological atlas" to characterize cells by location is one of the long-term goals of the International Brain Lab, they are collecting a massive dataset at the moment but I wouldn't expect something like that for a while still.
> 
> Barring that, the only sanity checks I know of are things like known LFP oscillations, clusters of firing properties, expected responses, spatial gaps between units, etc. So if you're recording around CA1 for example, hopefully you'll see a characteristic lack of spikes in the white matter above and below.
> 
> Would that kind of thing be good enough for your purposes, or have you had particular trouble identifying the location?

Hi, I would like to know, can we export the anatomical location of the NP tract (may be from .mat to .CSV file)  leveraging IBL "electrophysiological atlas" to double-check my registration?

**Comment by petersaj** [comment]
Which electrophysiological atlas are you referring to? I was talking about something potentially in the works but that doesn't exist yet as far as I know. 

If you're talking about importing tract coordinates into IBL apps, check out this thread which has info on how to do that:
https://github.com/petersaj/AP_histology/issues/17

**Comment by AthiemoneZero** [comment]
Yeah, what I did refer to is that from IBL apps. And I got the information I want from your comment, that's really good. Really appreciate your reply and look forward to the future electrophysiological atlas function!
