### ISSUE TITLE
AP_loadStructureTree

### ISSUE THREAD

**Issue by imontiel92** [petersaj/AP_histology#23]
Hello Peter,
I hope you are doing well. 
I cannot use the pipeline for processing histology because this error message appears (in the first step ):
st = AP_loadStructureTree([allen_atlas_path filesep 'structure_tree_safe_2017.csv']);
Unrecognized function or variable 'AP_loadStructureTree'.

How can I resolve it? 
Best,
Ivan

**Comment by petersaj** [comment]
Hi Ivan - this function is included in the top level of the repository [here](https://github.com/petersaj/AP_histology/blob/0bad51d033bfc9800a846f21488c791f64687122/AP_loadStructureTree.m), it's probably one of two things:

1) did you clone the whole repository? 
2) did you add the cloned repository to your matlab path?

**Comment by imontiel92** [comment]
Thank you. The problem was I didn't cloned the whole repository. Sorry for the late reply.
