### ISSUE TITLE
channel's cordiantes 

### ISSUE THREAD

**Issue by parviz-gh** [petersaj/AP_histology#25]
Hi Andrew,
Thanks a lot for your pipeline. It works nicely. 
Once we have obtained probe_ccf.mat, where we have trajectory_areas and trajectory_cords corresponding to each probe, how do we assign each neuropixel channel its unique area and coordinate? Is there a script that I could use?”

**Comment by petersaj** [comment]
There are a couple possible ways to do this, probably none of them very smooth at the moment, but might depend on your particular prep: 

- In my own experiments, I used an electrophysiological landmarks to sync a channel with a spot on the trajectory, either the first unit after a space (which was a ventricle) or the border between a channel outside and inside the cortex. I did this programmatically for each experiment: load in the trajectory, calculate the landmark, and then assign spikes to areas based on that.
- I have a function to try to slide the trajectory up and down to match electrophysiological landmarks (https://github.com/petersaj/AP_histology#ap_align_probe_histology). I haven't developed that much, and another member of the lab made an updated version: https://github.com/EnnyvanBeest/GeneralNeuropixelAnalysisFunctions/blob/main/Histology/alignatlasdata.m
- the IBL also has a tool to do this: https://github.com/int-brain-lab/iblapps/tree/master/atlaselectrophysiology, which requires some conversion of the probe_ccf.mat into their standards, there's a thread on doing that here: https://github.com/petersaj/AP_histology/issues/17

I hope to make this process better in the next few months, but hopefully one of these things will work in the meantime
