### ISSUE TITLE
Problem loading histology_ccf.mat

### ISSUE THREAD

**Issue by spritefullake** [petersaj/AP_histology#3]
It seems there is problems in the program in generating the histology_ccf.mat. Is there an additional file dependency that needs to be added? The program pops up and can go through the rotation section and the start of alignment as well as save modified images. But the program errors after this. 

The error output is:

```
Done.
Error using load
Unable to read file 'D:\Brain slices\slices\histology_ccf.mat'. No such file
or directory.

Error in AP_auto_align_histology_ccf (line 19)
load(ccf_slice_fn);

Error in demo_histology_pipeline (line 44)
AP_auto_align_histology_ccf(slice_path);

Error in run (line 91)
evalin('caller', strcat(script, ';'));
```

**Comment by petersaj** [comment]
Hi Talha - did AP_grab_histology_ccf work for you, where you were able to save a corresponding CCF slice for each histology slice? That's the step that generates the histology_ccf.mat file that's missing in your case
