### ISSUE TITLE
Understanding of probe trajectories in 3D fig

### ISSUE THREAD

**Issue by Tan-Lao** [petersaj/AP_histology#30]
Hi , prof peter，

After running the Utilize aligned CCF function, I will get a 3D map of the brain and probe trajectories. I have looked at the paper you cited earlier, but I still do not understand what these points near the probe represent?

**Comment by petersaj** [comment]
Hi Tan-Lao - if I understand the question correctly: when you get the 3D view of the probe trajectory in the brain, the points represent where you clicked on the probe in the histology, and the line is the line of best fit through those points.

**Comment by Tan-Lao** [comment]
Thanks so much， Prof Peter. I also thought so before, but I did not find the exact expression so I am not sure. Thank you for your answer.
