### ISSUE TITLE
Error displaying Neuropixels trajectory

### ISSUE THREAD

**Issue by NJamann** [petersaj/AP_histology#31]
Hi Andy,

I get the following error when doing the Neuropixels alignment step after closing the alignment window:

**Error using yline (line 29)
Passing multiple values to ConstantLine is not supported.

Error in ap_histology.annotate_neuropixels>plot_probe (line 246)
    yline(unique(trajectory_areas_boundaries(:)),'color','k','linewidth',1);

Error in ap_histology.annotate_neuropixels>close_gui (line 390)
        plot_probe(gui_data,probe_ccf);

Error in iptaddcallback/callbackProcessor (line 149)
                    fun(varargin{:});
 
Error while evaluating DestroyedObject CloseRequestFcn.**

I don't know if this is relevant, but I just updated the repository from an old AP-histology version that still had the pipeline without the GUI. However, I repeated all the steps with the new version to make sure its not a compatibility issue.

Best,
Nora

**Comment by petersaj** [comment]
Hi Nora - that looks like a matlab version issue, that particular feature was added in R2021a. 

Is there a chance you could update your matlab to a newer version? I could make this one feature call work for old versions, but then you might run into other snags.

**Comment by NJamann** [comment]
Hi Andy,
ah thanks yes I can also run it on a newer version!
