### ISSUE TITLE
Missing functions?

### ISSUE THREAD

**Issue by RobertodelaTorre** [petersaj/AP_histology#33]
Hi Peter,

I tried to use your code and the demo_histology_pipeline for aligning my brain slices; however, I can't manage to make the code run. I have the feeling that some functions are missing in the GitHub repository. For instance, AP_process_histology, AP_rotate_histology, AP_grab_histology_ccf, and AP_auto_align_histology_ccf. Some others might have different names. Is it possible that I cloned the wrong repository?

Thanks!

**Comment by petersaj** [comment]
That was from an older version of the code, I've removed `demo_histology_pipeline` from the current repo to clarify that. 

The new version of the code puts all function into a GUI toolbar that you run with `AP_histology` - see the readme on the front page for directions

**Comment by RobertodelaTorre** [comment]
Thanks, Andy for your fast reply!

I tried the GUI at the beginning, but I couldn't see anything. That's why I moved to the old version. Now, I just found that there was a problem with the format of my images; they were not recognized. I tried now with a different format, and it works.
