### ISSUE TITLE
Python implementation?

### ISSUE THREAD

**Issue by AngCamp** [petersaj/AP_histology#34]
Is there a python implementation of this library?

**Comment by petersaj** [comment]
Nope, all matlab and no plans to move to python at the moment

**Comment by AngCamp** [comment]
Can you recommend a python implementation that has similar functionality?

**Comment by petersaj** [comment]
Sure, here are some options, with videos on how to use from the UCL Neuropixels course: 
- HERBS [github](https://github.com/Whitlock-Group/HERBS) , [video](https://www.youtube.com/watch?v=NDHO6IJCN1k&ab_channel=MatteoCarandini)
- IBL ephys alignment tool [github](https://github.com/int-brain-lab/iblapps/wiki) , [video](https://www.youtube.com/watch?v=HJC08wW0H4w&ab_channel=MatteoCarandini)
- Brainglobe (I think just for 3D histology at the moment?) [website](https://brainglobe.info/) , [video](https://www.youtube.com/watch?v=JQ-vYx42L6s&ab_channel=MatteoCarandini)
