### ISSUE TITLE
Code error "Expected input number 2, ANGLE, to be real.

### ISSUE THREAD

**Issue by AdaQianLI** [petersaj/AP_histology#4]
The angle_diff matrix being generated by function "AP_rotate_histology" is not in real value, which brings the error when processing the function "imrotate:
Error using imrotate 
Expected input number 2, ANGLE, to be real.
Can I kindly ask any setting mistake did I make? Or is the angle being generated in the wrong unit? Thanks in advance!

**Comment by petersaj** [comment]
Hi - to check: does this mean the reference line you're using is horizontal? Looks like it can't do that at the moment (it assumes vertical) but I can update it. Out of curiosity, what horizontal reference line can you get consistently?

**Comment by AdaQianLI** [comment]
Got you. I guess it's because I orient my coronal slice in vertical when taking picture and get the the reference line in horizontal. If so, is it an easy solution to rotate my figure in 90 degree first?

**Comment by petersaj** [comment]
I just pushed a fix that lets you use a reference line in any orientation, want to check and see if that works?

(or if your slices are rotated 90 deg from where you want them, probably easiest if you're on windows is to select all the slice images in explorer, right click and hit 'rotate left/right')

**Comment by AdaQianLI** [comment]
Would love to! Where to check out the new fix? Thanks in advance!

**Comment by petersaj** [comment]
You can just pull the updated repo however you use github and then try the function again
