### ISSUE TITLE
Sagittal Slices

### ISSUE THREAD

**Issue by Newtstein** [petersaj/AP_histology#6]
Hi there! 

Thanks so much for making this available for us! I was just wondering how I can incorporate images of brain slices in the sagittal plane. 

Thank you for your time!

**Comment by petersaj** [comment]
Hi - any direction slice should work, you can just rotate the atlas to
match the orientation of the slice. Have you had trouble with it?

**Comment by Newtstein** [comment]
Hi! 

Thank you so much for that! It's working now! 

I was also wondering whether or not I can align only a portion of the brain. For example, the images I am working with only capture the cerebellum in the sagittal plane. Is there any way this would work?

Thank you again for your immediate help!

**Comment by petersaj** [comment]
There's no automated way to estimate alignment to partial slices, but if
you do the manual alignment step hopefully it should work alright?

**Comment by Newtstein** [comment]
Hey Andy! 

Thanks for that! The manual alignment step worked perfectly.

My apologies for being a novice with MATLAB, but I seem to be encountering this error and cannot figure out how to solve it. Whenever you get the chance, let me know what is wrong.

I sincerely appreciate your help.

Error: 
<img width="500" alt="Screen Shot 2021-08-17 at 5 04 31 PM" src="https://user-images.githubusercontent.com/87092669/129800399-1f7b5c52-c1ac-4e5b-a7ce-e266a944bc25.png">

<img width="500" alt="Screen Shot 2021-08-17 at 5 07 25 PM" src="https://user-images.githubusercontent.com/87092669/129800777-b9e3de44-9f8d-4752-9b1d-7542903b92c9.png">

**Comment by petersaj** [comment]
That function used to come from a different repository (
https://github.com/cortex-lab/allenCCF), but it only used a few functions
so I copied them over to remove the dependency.

If you pull the current repo and make sure all the folders are in the path
it should work now?
