### ISSUE TITLE
Issue with Labeling 10+ probes in get_probe_histology

### ISSUE THREAD

**Issue by kangelaa** [petersaj/AP_histology#9]
When trying to label more than 9 probes in get_probe_histology, the program doesn't allow for inputting multiple numbers (to label probes 10, 11, 12, etc.). Is there a workaround for this?

**Comment by petersaj** [comment]
Just pushed a fix: now the 0 key = probe 10 and the shift key = +10 (shift+5 = probe 15) to support up to 20 probes with 20 unique colors.

Want to try that and make sure it works for you?

**Comment by kangelaa** [comment]
Seems to work well, thank you!
